server:
  port: 3000

spring:
  datasource:
    url: jdbc:h2:file:./h2/app_db;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
